"""
LexaGPT AI Service
Handles model inference with streaming support.
In DEBUG mode: uses template-based demo responses
In PRODUCTION mode: loads real trained models
"""
import time
import random
import logging
from typing import Generator, Dict, Any, List
from django.conf import settings

logger = logging.getLogger('core')


class LexaAIService:
    """
    Core AI inference service for LexaGPT platform.
    Supports streaming responses and multiple model variants.
    """

    DEMO_RESPONSES = [
        "I'm Lexa, your AI assistant. In production mode, I'll be powered by our custom-trained models. For now, this is a demonstration of the streaming interface. How can I help you today?",
        "That's a great question! Let me think through this carefully. The LexaGPT platform uses our proprietary Lexa model family, trained specifically for helpfulness, accuracy, and safety.",
        "I understand what you're asking. Here's my analysis:\n\n**Key Points:**\n- This is running in demo mode\n- Real responses come from our trained Lexa models\n- The streaming interface you see here is fully functional\n\nIn production, responses will be generated by the actual Lexa neural network.",
        "```python\n# Here's an example of the code\ndef hello_lexa():\n    print('Hello from LexaGPT!')\n    return 'AI powered by Lexa models'\n\nhello_lexa()\n```\n\nThis demonstrates our code artifact generation capability.",
        "Let me break this down step by step:\n\n1. First, I analyze your input\n2. Then I search my knowledge\n3. I formulate a coherent response\n4. Finally, I stream it to you in real-time\n\nThis is how the Lexa model pipeline works!",
    ]

    def __init__(self):
        self.models_loaded = {}
        self.is_debug = settings.DEBUG

        if not self.is_debug:
            self._load_models()

    def _load_models(self):
        """Load production models (only in production)"""
        try:
            import torch
            from transformers import AutoModelForCausalLM, AutoTokenizer

            for model_id, config in settings.LEXA_MODELS.items():
                model_path = config.get('model_path')
                if model_path:
                    logger.info(f"Loading model: {model_id} from {model_path}")
                    try:
                        tokenizer = AutoTokenizer.from_pretrained(model_path)
                        model = AutoModelForCausalLM.from_pretrained(
                            model_path,
                            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
                            device_map='auto',
                        )
                        self.models_loaded[model_id] = {
                            'model': model,
                            'tokenizer': tokenizer,
                        }
                        logger.info(f"Model {model_id} loaded successfully")
                    except Exception as e:
                        logger.error(f"Failed to load {model_id}: {e}")
        except ImportError:
            logger.warning("PyTorch/Transformers not available")

    def stream_response(
        self,
        prompt: str,
        history: List[Dict],
        model_id: str,
        user
    ) -> Generator[Dict[str, Any], None, None]:
        """
        Stream AI response token by token.
        Yields dicts with type='text' or type='done'
        """
        if self.is_debug:
            yield from self._demo_stream(prompt, model_id)
        else:
            yield from self._production_stream(prompt, history, model_id, user)

    def _demo_stream(self, prompt: str, model_id: str) -> Generator[Dict, None, None]:
        """Demo streaming with realistic delay"""
        # Select a contextual response
        response = self._get_contextual_demo_response(prompt)

        total_tokens = 0
        words = response.split(' ')

        for i, word in enumerate(words):
            chunk = word + (' ' if i < len(words) - 1 else '')
            yield {'type': 'text', 'text': chunk}
            total_tokens += 1
            time.sleep(0.03)  # Simulate token generation speed

        yield {'type': 'done', 'tokens': total_tokens}

    def _get_contextual_demo_response(self, prompt: str) -> str:
        """Generate contextual demo response based on prompt keywords"""
        prompt_lower = prompt.lower()

        if any(word in prompt_lower for word in ['code', 'python', 'javascript', 'function', 'program']):
            return f"""Here's a solution for your coding request:

```python
# LexaGPT Demo Code Generation
def solution():
    \"\"\"
    Generated by Lexa AI - Demo Mode
    Real code generation available in production
    \"\"\"
    # Your code logic here
    result = []
    for item in range(10):
        result.append(item ** 2)
    return result

# Run the solution
output = solution()
print(f"Result: {{output}}")
```

This demonstrates Lexa's code generation capability. In production, this would be actual working code tailored to your request."""

        elif any(word in prompt_lower for word in ['math', 'calculate', 'compute', 'equation']):
            return """Let me solve this mathematically.

**Step 1:** Parse the problem
**Step 2:** Apply relevant formulas
**Step 3:** Calculate the result

In production mode, Lexa uses specialized mathematical reasoning trained on millions of mathematical problems. The model can handle calculus, linear algebra, statistics, and more.

*Demo mode active - connect real Lexa models for actual computation*"""

        elif any(word in prompt_lower for word in ['hello', 'hi', 'hey', 'greet']):
            return f"""Hello! 👋 I'm **Lexa**, your AI assistant from LexaGPT.

I'm currently running in **demo mode**. In full production:
- I'll be powered by the Lexa model family
- Trained on diverse, high-quality datasets
- Capable of reasoning, coding, analysis, and creative tasks

What would you like to explore today?"""

        elif any(word in prompt_lower for word in ['explain', 'what is', 'how does', 'describe']):
            return f"""Great question! Let me explain this in detail.

**Overview:**
LexaGPT is a next-generation AI platform with our proprietary Lexa model family. This demo shows the platform's full capabilities.

**Key Features:**
1. **Streaming responses** - Real-time token generation
2. **Multi-modal support** - Text, code, and vision
3. **Long context** - Up to 1M tokens with Lexa Ultra
4. **Custom training** - Train models on your specific data

**Technical Details:**
In production, Lexa models use transformer architecture with advanced training techniques including RLHF and Constitutional AI methods.

*This is demo mode. Production responses come from actual trained models.*"""

        else:
            # Pick a random demo response
            response = random.choice(self.DEMO_RESPONSES)
            # Add user prompt context
            return f"""Regarding your message: *"{prompt[:50]}{'...' if len(prompt) > 50 else ''}"*

{response}

---
*🔧 Demo Mode: LexaGPT is running without a loaded model. Train your Lexa models through the admin training platform to get real AI responses.*"""

    def _production_stream(
        self,
        prompt: str,
        history: List[Dict],
        model_id: str,
        user
    ) -> Generator[Dict, None, None]:
        """Production inference with real models"""
        try:
            import torch

            if model_id not in self.models_loaded:
                # Fallback to demo if model not loaded
                yield from self._demo_stream(prompt, model_id)
                return

            model_data = self.models_loaded[model_id]
            model = model_data['model']
            tokenizer = model_data['tokenizer']

            # Build prompt with history
            conversation_text = self._build_conversation_prompt(prompt, history, tokenizer)

            inputs = tokenizer.encode(conversation_text, return_tensors='pt')
            if torch.cuda.is_available():
                inputs = inputs.cuda()

            # Get max tokens from plan
            max_tokens = settings.SUBSCRIPTION_PLANS.get(
                user.current_plan, {}
            ).get('features', {}).get('max_context_tokens', 8192)

            total_tokens = 0
            with torch.no_grad():
                for output in self._generate_streaming(model, inputs, max_new_tokens=min(2048, max_tokens)):
                    token_text = tokenizer.decode([output], skip_special_tokens=True)
                    if token_text:
                        yield {'type': 'text', 'text': token_text}
                        total_tokens += 1

            yield {'type': 'done', 'tokens': total_tokens}

        except Exception as e:
            logger.error(f"Production inference error: {e}")
            yield from self._demo_stream(prompt, model_id)

    def _build_conversation_prompt(self, prompt: str, history: List[Dict], tokenizer) -> str:
        """Build full conversation prompt from history"""
        messages = []
        messages.append({"role": "system", "content": "You are Lexa, a helpful AI assistant created by LexaGPT."})
        for msg in history[-20:]:  # Last 20 messages for context
            messages.append({"role": msg['role'], "content": msg['content']})
        messages.append({"role": "user", "content": prompt})

        # Try chat template if available
        if hasattr(tokenizer, 'apply_chat_template'):
            return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

        # Fallback format
        text = "System: You are Lexa, a helpful AI assistant.\n\n"
        for msg in messages[1:]:
            prefix = "Human: " if msg['role'] == 'user' else "Assistant: "
            text += f"{prefix}{msg['content']}\n"
        text += "Assistant: "
        return text

    def _generate_streaming(self, model, inputs, max_new_tokens=2048):
        """Yield tokens one by one"""
        import torch
        from transformers import StoppingCriteria, StoppingCriteriaList

        generated = inputs
        for _ in range(max_new_tokens):
            with torch.no_grad():
                outputs = model(generated)
                next_token = outputs.logits[:, -1, :].argmax(dim=-1)
                generated = torch.cat([generated, next_token.unsqueeze(0)], dim=-1)
                yield next_token.item()
                # Stop on EOS
                if next_token.item() == model.config.eos_token_id:
                    break